ruby_on_rails/sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'

  root               'static_pages#home'
  get 'help'      => 'static_pages#help'
  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'signup'    => 'users#new'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do 
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

ruby_on_rails/sample_app/app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<small>
			<%= link_to "Chatter", root_url %>
		</small>
		<nav>
			<ul>
				<li><%= link_to image_tag("github4.svg", alt: "Github logo"), 'http://www.github.com/cameronjkelley' %></li>
				<li><%= link_to image_tag("linkedin2.svg", alt: "LinkedId logo"), 'http://www.linkedin.com/in/cameronjkelley' %></li>
			</ul>
		</nav>
	</div>
</footer>

ruby_on_rails/sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
		    <span class="sr-only">Toggle navigation</span>
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
	    </button>
		<%= link_to "Chatter", root_path, id: "logo" %>
		<div class="collapse navbar-collapse">
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<% if logged_in? %>
						<li><%= link_to "Home", root_path %></li>
						<li><%= link_to "Users", users_path %></li>
						<li class="dropdown">
							<a href='#' class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<%= link_to "Log out", logout_path, method: :delete %></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Log In", login_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

ruby_on_rails/sample_app/app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

ruby_on_rails/sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<% flash.each do |msg_type, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-#{msg_type}") %>		
		<% end %>
		<div class="container">
			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</body>
</html>