ruby_on_rails/private-events/config/routes.rb
Rails.application.routes.draw do
  root               'events#index'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users, only: [:new, :create, :show, :index]
  resources :events, only: [:new, :create, :show, :index]
end

ruby_on_rails/private-events/app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  has_many :invites, foreign_key: "attended_event_id"
  has_many :attendees, through: :invites

  scope :upcoming, -> { where("Date >= ?", Date.today).order("Date ASC") }
  scope :past,     -> { where("Date < ?", Date.today).order("Date DESC") }
end

ruby_on_rails/private-events/app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

ruby_on_rails/private-events/app/models/user.rb
class User < ActiveRecord::Base
  has_many :events, foreign_key: "creator_id"
  has_many :invites, foreign_key: "attendee_id"
  has_many :attended_events, through: :invites

  has_secure_password

  def upcoming_events
    self.attended_events.upcoming 
  end

  def past_events
    self.attended_events.past 
  end

  def attend!(event)
    self.invites.create!(attended_event_id: event.id)
  end

  def attending?(event)
    event.attendees.inlcude?(self)
  end
end

ruby_on_rails/private-events/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

ruby_on_rails/private-events/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to event_path(@event)
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.all
  end

  private

    def event_params
      params.require(:event).permit(:date, :event_time, :title, :description)
    end
end

ruby_on_rails/private-events/app/controllers/invites_controller.rb
class InvitesController < ApplicationController
end

ruby_on_rails/private-events/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      log_in user
      redirect_to user 
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

ruby_on_rails/private-events/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user 
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @events = @user.events
    @upcoming_events = @user.upcoming_events
    @past_events = @user.past_events
  end

  def index
    @users = User.all 
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

ruby_on_rails/private-events/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby_on_rails/private-events/app/helpers/events_helper.rb
module EventsHelper
end

ruby_on_rails/private-events/app/helpers/invites_helper.rb
module InvitesHelper
end

ruby_on_rails/private-events/app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id 
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end
end

ruby_on_rails/private-events/app/helpers/users_helper.rb
module UsersHelper
end

ruby_on_rails/private-events/app/views/events/index.html.erb
<div class="page-header">
	<h1>All Events</h1>
</div>
<div class="row">
	<div class="col-xs-2">
		<h4>Event</h4>
	</div>
	<div class="col-xs-2">
		<h4>Date</h4>
	</div>
	<div class="col-xs-2">
		<h4>Time</h4>
	</div>
	<div class="col-xs-2">
		<h4>Attending</h4>
	</div>
</div>
<% @events.each do |event| %>
	<div class="row">
		<div class="col-xs-2">
			<p><%= link_to event.title, event_path(event) %></p>
		</div>
		<div class="col-xs-2">
			<p><%= event.date.strftime("%B %d, %Y") %></p>
		</div>
		<div class="col-xs-2">
			<p><%= event.event_time.strftime("%I:%M %p") %></p>
		</div>
		<div class="col-xs-2">
			<p><%= event.attendees.count %></p>
		</div>
	</div>
<% end %>

ruby_on_rails/private-events/app/views/events/new.html.erb
<div class="page-header">
	<h3>Create an Event</h3>
</div>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @event do |f| %>
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control' %>

			<%= f.label :description %>
			<%= f.text_area :description, class: 'form-control' %>

			<%= f.label :date %>
			<%= f.date_field :date, class: 'form-control' %>

			<%= f.label :event_time %>
			<%= f.time_field :event_time, class: 'form-control' %>

			<%= f.submit 'Create Event', class: 'btn btn-primary' %>
		<% end %>
	</div>
</div>

ruby_on_rails/private-events/app/views/events/show.html.erb
<h4><%= @event.title %></h4>
<p><%= @event.date.strftime("%B %d, %Y") %> at <%= @event.event_time.strftime("%I:%M %p")%></p>
<p><%= @event.description %></p>

<h5>Attending</h5>
<ol>
<% @event.attendees.each do |attendee| %>
	<li><%= attendee.name %></li>
<% end %>
</ol>

ruby_on_rails/private-events/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
		    <span class="sr-only">Toggle navigation</span>
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
	    </button>
		<div class="navbar-header">
			<h3 id="navbar-brand">private events</h3>
		</div>
		<div class="collapse navbar-collapse">
			<nav>
				<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Events', events_path %></li>
				<li><%= link_to 'Users', users_path %></li>
				<% if logged_in? %>
					<li><%= link_to 'Log out', logout_path, method: :delete %></li>
				<% else %>
					<li><%= link_to 'Log in', login_path %></li>
				<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

ruby_on_rails/private-events/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>PrivateEvents</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
		</div>
		<%= debug(params) if Rails.env.development? %>
	</body>
</html>

ruby_on_rails/private-events/app/views/users/_user_events.html.erb
<% object.each do |event| %>
	<div class="row">
		<div class="col-xs-2">
			<p><%= event.date.strftime("%B %d, %Y") %></p>
		</div>
		<div class="col-xs-2">
			<p><%= event.event_time.strftime("%I:%M %p")  %></p>
		</div>
		<div class="col-xs-2">
			<p><%= link_to event.title, event_path(event) %></p>
		</div>
		<div class="col-xs-2">
			<p><%= event.attendees.count %></p>
		</div>
	</div>
<% end %>

ruby_on_rails/private-events/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

ruby_on_rails/private-events/app/views/users/index.html.erb
<div class="page-header">
	<h1>All Users</h1>
</div>

<% @users.each do |user| %>
	<ol>
		<li><%= user.name %></li>
	</ol>
<% end %>

ruby_on_rails/private-events/app/views/users/new.html.erb
<div class="page-header">
	<h1 class="col-md-offset-3">Sign Up</h1>
</div>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @user do |f| %>	
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Sign up", class: 'btn btn-primary' %>
		<% end %>
	</div>
</div>

ruby_on_rails/private-events/app/views/users/show.html.erb
<div class="page-header">
	<div class="row">
		<div class="col-xs-6">
			<h3><%= @user.name %></h3>
		</div>
		<div class="col-xs-6 text-right" id="create-button">
			<%= link_to "Create an event", new_event_path, class: 'btn btn-primary' %>
		</div>
	</div>
</div>
<div class="user-events">
	<h4>Your Events</h4>
	<%= render 'users/user_events', object: @events %>
	<h4>Upcoming Events</h4>
	<%= render 'users/user_events', object: @upcoming_events %>	
	<h4>Past Events</h4>
	<%= render 'users/user_events', object: @past_events %>	
</div>